### ISSUE TITLE
Ladezeit des Hintergrundbildes

### ISSUE THREAD

**Issue by harmoniemand** [susanne-h/susanne-h.github.io#1]
Ahoi,

kleiner Tipp. Das Hintergrundbild lädt ewig, selbst mit einer sehr schnellen Leitung.

Versucht das mal als PNG zu hinterlegen und am besten auch die Bitrate heruntersetzten. Da am besten ein wenig experimentieren, dass es noch gut aussieht aber schneller lädt.

**Comment by lukas-h** [comment]
Das lässt sich einrichten. Danke!

**Comment by lukas-h** [comment]
bissel besser, einigermaßen akzeptabel jetzt
